# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Henning's Blog
description: My personal blog where I reflect upon everything around data science, AI, endurance sports, vegan food and just everything else I think about.
github_username: henninglebbaeus

# Email and twitter are optional:
email: 
twitter_username: HenningLebbaeus

# Set this to true to get LaTeX math equation support
use_math: 

# Everything below here can be ignored, unless you want to change the theme entirely
theme: architect
plugins:
  - jekyll-feed

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
